version: '2'

services:
  product:
    build: 
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: npm run start:dev product
    env_file:
      - ./apps/product/.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    volumes:
      - .:/usr/src/apps
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
  mongodb-primary:
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'
  administrator:
    build:
      context: .
      dockerfile: ./apps/administrator/Dockerfile
      target: development
    command: npm run start:dev administrator
    env_file:
      - ./apps/administrator/.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
    volumes:
      - .:/usr/src/apps
      - /usr/src/app/node_modules
    ports:
      - '8081:8081'
  permission:
    build:
      context: .
      dockerfile: ./apps/permission/Dockerfile
      target: development
    command: npm run start:dev permission
    env_file:
      - ./apps/permission/.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
      - administrator
    volumes:
      - .:/usr/src/apps
      - /usr/src/app/node_modules
    ports:
      - '8082:8082'
  role:
    build:
      context: .
      dockerfile: ./apps/role/Dockerfile
      target: development
    command: npm run start:dev role
    env_file:
      - ./apps/role/.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq
      - administrator
      - permission
    volumes:
      - .:/usr/src/apps
      - /usr/src/app/node_modules
    ports:
      - '8083:8083'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:7.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:7.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
